# -- Site Settings --
title: hica Documentation
description: "A modern, safe, expression-oriented, functional-flavored language with a gentle learning curve."
keywords: "hica, programming language, koka, algebraic effects, systems language, functional programming"

url: "https://www.hica.dev"
baseurl: ""

# -- Build Settings --
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# -- Plugins --
plugins:
  - jekyll-feed

permalink: pretty

# -- Exclude non-site files --
exclude:
  - src
  - lib
  - tests
  - examples
  - learn
  - prelude
  - hica
  - test-hica.sh
  - AUTHORS
  - LICENSE
  - Makefile
  - README.md
  - documentation
  - .github
  - .gitignore
  - .gitmodules
  - .tbdflow.yml
  - Gemfile.lock
  - CNAME
