// examples/auto_derive_eq.hc
//
// Auto-derived (==) for user-defined types.
//
// Every `type` (enum) and `struct` gets a structural equality operator
// generated by the compiler. Structs are equal iff every field is equal;
// enum values are equal iff they are the same variant and every payload
// field is equal. Field equality dispatches through the field's own
// `(==)`, so nested user types and containers Just Work.
//
// Note: `if x == Ctrl { ... }` parses `Ctrl { ... }` as a struct literal
// because `Name {` is greedy in expression position. Parenthesise the
// condition — `if (x == Ctrl) { ... }` — to disambiguate.

type Modifier {
  Ctrl, Alt, Meta, Shift
}

type Key {
  KChar(c: char),
  KShortcut(m: Modifier, c: char)
}

struct Position {
  line: int,
  col: int
}

fun main() {
  // No-payload enums: variant-tag comparison.
  println(show(Ctrl == Ctrl))                       // True
  println(show(Ctrl == Alt))                        // False

  // Payload enums: variant + field-wise comparison.
  println(show(KShortcut(Ctrl, 'q') == KShortcut(Ctrl, 'q')))  // True
  println(show(KShortcut(Ctrl, 'q') == KShortcut(Alt, 'q')))   // False
  println(show(KChar('x') == KShortcut(Ctrl, 'q')))            // False

  // Structs: field-wise comparison.
  println(show(Position { line: 3, col: 5 } == Position { line: 3, col: 5 }))  // True
  println(show(Position { line: 3, col: 5 } == Position { line: 4, col: 5 }))  // False

  // Use in a helper. No hand-written `match { Ctrl => true, _ => false }`
  // helper required.
  let m: Modifier = Ctrl
  let is_ctrl = (m == Ctrl)
  if is_ctrl { println("ctrl held") } else { println("not ctrl") }
}
