#!/usr/bin/env bash
set -euo pipefail

# bundle-stdlib.sh — Embed stdlib .hc sources into a Koka module
#
# Generates src/stdlib-bundle.kk with each stdlib file as a (path, source) pair.
# This allows the hica binary to work without external stdlib files.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$SCRIPT_DIR/.."
OUT="$ROOT/src/stdlib-bundle.kk"

# Format: "module-path:relative-file-path"
STDLIB_FILES=(
  "std/term:stdlib/std/term.hc"
  "std/ops:stdlib/std/ops.hc"
  "std/list:stdlib/std/list.hc"
  "std/string:stdlib/std/string.hc"
  "std/io:stdlib/std/io.hc"
  "std/actor:stdlib/std/actor.hc"
  "std/datetime:stdlib/std/datetime.hc"
  "std/cli:stdlib/std/cli.hc"
  "std/env:stdlib/std/env.hc"
)

echo "Bundling ${#STDLIB_FILES[@]} stdlib file(s) into $OUT ..."

{
  cat <<'HEADER'
// Auto-generated by scripts/bundle-stdlib.sh — do not edit
// Embedded stdlib .hc sources so the binary works without external files.
module stdlib-bundle

pub fun embedded-stdlib-sources() : list<(string, string)>
  [
HEADER

  for entry in "${STDLIB_FILES[@]}"; do
    mod_path="${entry%%:*}"
    rel_file="${entry##*:}"
    filepath="$ROOT/$rel_file"
    if [ ! -f "$filepath" ]; then
      echo "ERROR: $filepath not found" >&2
      exit 1
    fi
    echo -n "    (\"${mod_path}\", \""
    first=true
    while IFS= read -r line || [ -n "$line" ]; do
      if [ "$first" = true ]; then
        first=false
      else
        echo -n '\n'
      fi
      # Escape backslashes first, then double-quotes
      escaped=$(printf '%s' "$line" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')
      echo -n "$escaped"
    done < "$filepath"
    echo '"),'
  done

  echo "  ]"
} > "$OUT"

echo "Done: $(wc -l < "$OUT") lines"
