#!/usr/bin/env bash
set -euo pipefail

# bundle-kk-stdlib.sh — Embed native Koka stdlib files into src/stream-kk-bundle.kk
#
# These are .kk files (not hica sources) that back built-in types.
# Generated file: src/stream-kk-bundle.kk

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$SCRIPT_DIR/.."
OUT="$ROOT/src/stream-kk-bundle.kk"

KK_FILES=(
  "hc-stream:stdlib/std/stream.kk"
)

echo "Bundling ${#KK_FILES[@]} Koka stdlib file(s) into $OUT ..."

{
  cat <<'HEADER'
// Auto-generated by scripts/bundle-kk-stdlib.sh — do not edit
// Embedded native Koka stdlib sources for built-in types (stream<a> etc.).
module stream-kk-bundle

pub fun embedded-kk-stdlib-sources() : list<(string, string)>
  [
HEADER

  for entry in "${KK_FILES[@]}"; do
    mod_name="${entry%%:*}"
    rel_file="${entry##*:}"
    filepath="$ROOT/$rel_file"
    if [ ! -f "$filepath" ]; then
      echo "ERROR: $filepath not found" >&2
      exit 1
    fi
    echo -n "    (\"${mod_name}\", \""
    first=true
    while IFS= read -r line || [ -n "$line" ]; do
      if [ "$first" = true ]; then
        first=false
      else
        echo -n '\n'
      fi
      escaped=$(printf '%s' "$line" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')
      echo -n "$escaped"
    done < "$filepath"
    echo '"),'
  done

  echo "  ]"
} > "$OUT"

echo "Done: $(wc -l < "$OUT") lines"
