#!/usr/bin/env bash
set -euo pipefail

# bundle-prelude.sh — Embed prelude .hc sources into a Koka module
#
# Generates src/prelude-bundle.kk with each prelude file as a string constant.
# This allows the hica binary to work without external prelude files.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$SCRIPT_DIR/.."
OUT="$ROOT/src/prelude-bundle.kk"

PRELUDE_FILES=(
  "prelude/math.hc"
  "prelude/operators.hc"
  "prelude/glob.hc"
  "prelude/lists.hc"
  "prelude/strings.hc"
  "prelude/datetime.hc"
  "prelude/cli.hc"
  "prelude/io.hc"
  "prelude/actors.hc"
)

echo "Bundling ${#PRELUDE_FILES[@]} prelude files into $OUT ..."

{
  cat <<'HEADER'
// Auto-generated by scripts/bundle-prelude.sh — do not edit
// Embedded prelude .hc sources so the binary works without external files.
module prelude-bundle

pub fun embedded-prelude-sources() : list<string>
  [
HEADER

  for pf in "${PRELUDE_FILES[@]}"; do
    filepath="$ROOT/$pf"
    if [ ! -f "$filepath" ]; then
      echo "ERROR: $filepath not found" >&2
      exit 1
    fi
    # Escape backslashes, then double-quotes for Koka string literals
    content=$(sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' "$filepath")
    # Write as a multi-line Koka raw string using triple-quote would be ideal,
    # but Koka uses regular strings. We'll join lines with \n.
    echo -n '    "'
    first=true
    while IFS= read -r line || [ -n "$line" ]; do
      if [ "$first" = true ]; then
        first=false
      else
        echo -n '\n'
      fi
      echo -n "$line"
    done < <(sed -e 's/\\/\\\\/g' -e 's/"/\\"/g' "$filepath")
    echo '",'
  done

  echo "  ]"
} > "$OUT"

echo "Done: $(wc -l < "$OUT") lines"
