// Auto-generated by build-playground.sh — do not edit
const PRELUDE_SOURCES = [
`// hica – math prelude
//
// This source file is part of the hica open source project
// Copyright (C) 2026 Claes Adamsson <claes.adamsson@gmail.com>
//
// See https://github.com/cladam/hica/blob/main/LICENSE for license information

fun abs(n) => if n < 0 { -n } else { n }

fun min(a, b) => if a < b { a } else { b }

fun max(a, b) => if a > b { a } else { b }

fun clamp(v, lo, hi) => min(max(v, lo), hi)

// Greatest Common Divisor (GCD)
fun gcd(a, b) => if b == 0 { a } else { gcd(b, a % b) }

// Least Common Multiple (LCM)
fun lcm(a, b) => if a == 0 || b == 0 { 0 } else { abs(a * b) / gcd(a, b) }

// Integer exponentiation
fun pow(base, exp) => if exp <= 0 { 1 } else { base * pow(base, exp - 1) }

// Sign function: returns -1, 0, or 1
fun sign(n) => if n > 0 { 1 } else if n < 0 { -1 } else { 0 }`,
`// hica – glob prelude
//
// Character classification and glob pattern matching.
// Provides is_digit, is_alpha, etc. for character-level checks,
// and glob_match for simple wildcard pattern matching (* and ?).
//
// This source file is part of the hica open source project
// Copyright (C) 2026 Claes Adamsson <claes.adamsson@gmail.com>
//
// See https://github.com/cladam/hica/blob/main/LICENSE for license information

// ---------------------------------------------------------------------------
// Character classification
// ---------------------------------------------------------------------------

// True if c is an ASCII digit (0–9)
fun is_digit(c: char) : bool {
  let n = ord(c)
  n >= 48 && n <= 57
}

// True if c is an ASCII uppercase letter (A–Z)
fun is_upper(c: char) : bool {
  let n = ord(c)
  n >= 65 && n <= 90
}

// True if c is an ASCII lowercase letter (a–z)
fun is_lower(c: char) : bool {
  let n = ord(c)
  n >= 97 && n <= 122
}

// True if c is an ASCII letter (a–z, A–Z)
fun is_alpha(c: char) : bool => is_upper(c) || is_lower(c)

// True if c is an ASCII letter or digit
fun is_alnum(c: char) : bool => is_alpha(c) || is_digit(c)

// True if c is an ASCII whitespace character
fun is_space(c: char) : bool {
  let n = ord(c)
  n == 32 || n == 9 || n == 10 || n == 13
}

// True if c is an ASCII punctuation character (printable, non-alnum, non-space)
fun is_punct(c: char) : bool {
  let n = ord(c)
  (n >= 33 && n <= 47) || (n >= 58 && n <= 64) || (n >= 91 && n <= 96) || (n >= 123 && n <= 126)
}

// ---------------------------------------------------------------------------
// String-level classification helpers
// ---------------------------------------------------------------------------

// True if every character in s is a digit
fun all_digits(s: string) : bool =>
  if str_length(s) == 0 { false }
  else { all(chars(s), is_digit) }

// True if every character in s is a letter
fun all_alpha(s: string) : bool =>
  if str_length(s) == 0 { false }
  else { all(chars(s), is_alpha) }

// True if every character in s is uppercase
fun all_upper(s: string) : bool =>
  if str_length(s) == 0 { false }
  else { all(chars(s), is_upper) }

// True if every character in s is lowercase
fun all_lower(s: string) : bool =>
  if str_length(s) == 0 { false }
  else { all(chars(s), is_lower) }

// True if every character in s is alphanumeric
fun all_alnum(s: string) : bool =>
  if str_length(s) == 0 { false }
  else { all(chars(s), is_alnum) }

// ---------------------------------------------------------------------------`,
];
