// Auto-generated by build-playground.sh — do not edit
const STDLIB_SOURCES = [
  ["std/term", `// hica standard library — terminal colors and styles
//
// ANSI escape code wrappers for colored/styled terminal output.
// Import with:  import "std/term"
//
// All functions wrap a string with ANSI SGR codes and reset to default after.
// Functions are composable: bold(red("error:")) works correctly.
//
// Example:
//   import "std/term"
//
//   fun main() {
//     println(green("OK"))
//     println(bold(red("error: something went wrong")))
//     println(cyan("info: ") + "all good")
//   }
//
// This source file is part of the hica open source project
// Copyright (C) 2026 Claes Adamsson <claes.adamsson@gmail.com>
//
// See https://github.com/cladam/hica/blob/main/LICENSE for license information

// ESC character (ASCII 27) — used to build ANSI escape sequences
pub fun term_esc() : string => char_to_string(chr(27))

// Apply an ANSI SGR code to text, resetting to default after.
// This is the building block for all color/style functions.
pub fun term_ansi(code: string, s: string) : string =>
  term_esc() + "[" + code + "m" + s + term_esc() + "[0m"

// ---------------------------------------------------------------------------
// Foreground colors
// ---------------------------------------------------------------------------

pub fun red(s: string) : string => term_ansi("31", s)
pub fun green(s: string) : string => term_ansi("32", s)
pub fun yellow(s: string) : string => term_ansi("33", s)
pub fun blue(s: string) : string => term_ansi("34", s)
pub fun magenta(s: string) : string => term_ansi("35", s)
pub fun cyan(s: string) : string => term_ansi("36", s)
pub fun white(s: string) : string => term_ansi("37", s)

// ---------------------------------------------------------------------------
// Text styles
// ---------------------------------------------------------------------------

pub fun bold(s: string) : string => term_ansi("1", s)
pub fun dim(s: string) : string => term_ansi("2", s)
pub fun italic(s: string) : string => term_ansi("3", s)
pub fun underline(s: string) : string => term_ansi("4", s)
pub fun strikethrough(s: string) : string => term_ansi("9", s)

// ---------------------------------------------------------------------------
// Bright foreground colors
// ---------------------------------------------------------------------------

pub fun bright_red(s: string) : string => term_ansi("91", s)
pub fun bright_green(s: string) : string => term_ansi("92", s)
pub fun bright_yellow(s: string) : string => term_ansi("93", s)
pub fun bright_blue(s: string) : string => term_ansi("94", s)
pub fun bright_cyan(s: string) : string => term_ansi("96", s)
pub fun bright_white(s: string) : string => term_ansi("97", s)

// ---------------------------------------------------------------------------
// True color (24-bit RGB) — requires a modern terminal
// Foreground: term_rgb(r, g, b, s)  — wraps s in \\e[38;2;R;G;Bm ... \\e[0m
// ---------------------------------------------------------------------------

pub fun term_rgb(r: int, g: int, b: int, s: string) : string =>
  term_esc() + "[38;2;" + show(r) + ";" + show(g) + ";" + show(b) + "m" + s + term_esc() + "[0m"

// ---------------------------------------------------------------------------
// Ilseon palette — inspired by github.com/cladam/ilseon
//
// A low-sensory, OLED-focused dark palette with organic and muted accents.
// Colours follow the "Pulse" spectrum (energy & priority) and semantic slots
// from the ilseon app theme.
//
// Requires true color terminal support (iTerm2, VS Code, most modern terminals).
// ---------------------------------------------------------------------------

pub fun ilseon_teal(s: string) : string => term_rgb(0, 191, 165, s)        // #00BFA5  TealAccent — primary action
pub fun ilseon_muted_red(s: string) : string => term_rgb(179, 95, 95, s)   // #B35F5F  MutedRed — urgent / priority high
pub fun ilseon_amber(s: string) : string => term_rgb(192, 138, 62, s)      // #C08A3E  QuietAmber — priority medium
pub fun ilseon_ochre(s: string) : string => term_rgb(226, 176, 94, s)      // #E2B05E  StatusHigh — warm ochre / high energy
pub fun ilseon_sage(s: string) : string => term_rgb(163, 169, 145, s)      // #A3A991  StatusMedium — muted sage / balanced
pub fun ilseon_slate(s: string) : string => term_rgb(125, 133, 151, s)     // #7D8597  StatusLow — steel blue-grey / low pressure
pub fun ilseon_muted_teal(s: string) : string => term_rgb(90, 155, 128, s) // #5A9B80  MutedTeal — green-teal accent
pub fun ilseon_blue_teal(s: string) : string => term_rgb(76, 154, 155, s)  // #4C9A9B  BlueTeal — secondary highlight
pub fun ilseon_slate_blue(s: string) : string => term_rgb(94, 109, 126, s) // #5E6D7E  SlateBlue — quiet UI element
pub fun ilseon_detail(s: string) : string => term_rgb(136, 136, 136, s)    // #888888  MutedDetail — secondary text / low priority

// ----------------------------------------------------------------------------
// hica unique palette
// ---------------------------------------------------------------------------- `],
  ["std/ops", `// hica – operator prelude
//
// Operators as first-class functions, inspired by Python's operator module.
// Pass these to map, filter, fold, etc. instead of writing lambdas.
//
//   fold(xs, 0, add)       // instead of fold(xs, 0, fun(a, b) => a + b)
//   filter(xs, is_positive) // instead of filter(xs, fun(n) => n > 0)
//
// This source file is part of the hica open source project
// Copyright (C) 2026 Claes Adamsson <claes.adamsson@gmail.com>
//
// See https://github.com/cladam/hica/blob/main/LICENSE for license information

// --- Arithmetic ---

pub fun add(a, b) => a + b

pub fun sub(a, b) => a - b

pub fun mul(a, b) => a * b

pub fun div(a, b) => a / b

pub fun mod(a, b) => a % b

pub fun neg(n) => -n

// --- Comparison ---

pub fun lt(a, b) => a < b

pub fun le(a, b) => a <= b

pub fun gt(a, b) => a > b

pub fun ge(a, b) => a >= b

// --- Logical ---

pub fun not_(b) => !b

pub fun and_(a, b) => a && b

pub fun or_(a, b) => a || b

// --- Predicates ---

pub fun is_positive(n) => n > 0

pub fun is_negative(n) => n < 0

pub fun is_zero(n) => n == 0

pub fun is_even(n) => n % 2 == 0

pub fun is_odd(n) => n % 2 != 0

// --- Utility ---

pub fun identity(x) => x

//fun square(n) => n * n

//fun double(n) => n * 2`],
  ["std/list", `// hica – list prelude
//
// Higher-level list functions built on top of the list primitives
// (map, filter, fold, etc.).
//
// This source file is part of the hica open source project
// Copyright (C) 2026 Claes Adamsson <claes.adamsson@gmail.com>
//
// See https://github.com/cladam/hica/blob/main/LICENSE for license information

// --- Transformations ---

pub fun intersperse(xs, sep) => match xs {
  [] => [],
  [x] => [x],
  [x, ..rest] => [x, sep] + intersperse(rest, sep)
}

// --- Reductions ---

pub fun sum(xs) => fold(xs, 0, (a, b) => a + b)

pub fun product(xs) => fold(xs, 1, (a, b) => a * b)

pub fun scan(xs, init, f) => match xs {
  [] => [init],
  [x, ..rest] => [init] + scan(rest, f(init, x), f)
}

// --- Combining ---

pub fun zip_with(xs, ys, f) => map(zip(xs, ys), (pair) => f(pair.0, pair.1))

// --- Filtering ---

pub fun unique(xs: list<int>) : list<int> => fold(xs, [], (acc, x) => if x in acc { acc } else { acc + [x] })

// --- Splitting ---

pub fun chunks(xs, n) => match xs {
  [] => [],
  _ => [take(xs, n)] + chunks(drop(xs, n), n)
}

// --- Head/Tail helpers ---

// First element or a default value (avoids unwrapping maybe after length check)
pub fun head_or(xs, default) => match xs {
  [] => default,
  [x, ..] => x
}

// --- Prefix/Suffix predicates ---

// Take elements from the front while predicate holds
pub fun take_while(xs, pred) => match xs {
  [] => [],
  [x, ..rest] => if pred(x) { [x] + take_while(rest, pred) } else { [] }
}

// Drop elements from the front while predicate holds; return the rest
pub fun drop_while(xs, pred) => match xs {
  [] => [],
  [x, ..rest] => if pred(x) { drop_while(rest, pred) } else { xs }
}

// --- Counting ---

// Count elements matching predicate
pub fun count(xs, pred) => fold(xs, 0, (acc, x) => if pred(x) { acc + 1 } else { acc })

// --- Grouping ---

// Internal helper: insert item into existing (key, group) pair list
pub fun group_by_insert(pairs, key: string, item) => match pairs {
  [] => [(key, [item])],
  [p, ..rest] => match p {
    (k, vs) => if k == key { [(k, vs + [item])] + rest } else { [(k, vs)] + group_by_insert(rest, key, item) }
  }
}

// Group elements by key function f(x) -> string; returns list of (key, group) pairs
pub fun group_by(xs, f) => fold(xs, [], (acc, x) => group_by_insert(acc, f(x), x))

// --- Min/Max by key ---

// Internal helpers (pub required for stdlib modules)
pub fun pick_min(a, b, ka: int, kb: int) => if ka < kb { a } else { b }
pub fun pick_max(a, b, ka: int, kb: int) => if ka > kb { a } else { b }

// Element with the smallest int key (None on empty list)
pub fun min_by(xs, f) => match xs {
  [] => None,
  [first, ..rest] => Some(fold(rest, first, (best, x) => pick_min(x, best, f(x), f(best))))
}

// Element with the largest int key (None on empty list)
pub fun max_by(xs, f) => match xs {
  [] => None,
  [first, ..rest] => Some(fold(rest, first, (best, x) => pick_max(x, best, f(x), f(best))))
}`],
  ["std/string", `// hica – string stdlib module
//
// Extended string functions. Auto-import with: import "std/string"
// Functions that depend on prelude internals (pad_left, pad_right, repeat_str,
// removeprefix) stay in the prelude until std/cli is separated.
//
// This source file is part of the hica open source project
// Copyright (C) 2026 Claes Adamsson <claes.adamsson@gmail.com>
//
// See https://github.com/cladam/hica/blob/main/LICENSE for license information

// --- Counting ---

pub fun count_substr(s: string, sub: string) => length(split(s, sub)) - 1

// --- Wrapping ---

pub fun surround(s: string, wrap: string) => wrap + s + wrap

// --- Case helpers ---

pub fun capitalise(s: string) : string =>
  if str_length(s) == 0 { "" }
  else { to_upper(s[:1]) + to_lower(s[1:]) }

pub fun capwords(s: string) : string =>
  join(map(filter(split(s, " "), (w) => str_length(w) != 0), (w) => capitalise(w)), " ")

pub fun shout(s: string) : string => to_upper(s) + "!"

// --- Suffix removal ---

pub fun removesuffix(s: string, suf: string) : string =>
  if ends_with(s, suf) { s[:str_length(s) - str_length(suf)] }
  else { s }

// --- Float formatting ---

// show() for floats inherits Koka's %g formatting which drops the decimal
// point for whole numbers (1.0 → "1"). show_float always includes it,
// making it correct for formats like JSON that require 1.0 not "1".
// Scientific notation (1e+10) is left unchanged — it already signals float.
pub fun show_float(n: float) : string =>
  let s = show(n)
  if contains(s, ".") || contains(s, "e") { s }
  else { s + ".0" }`],
  ["std/datetime", `// hica – datetime stdlib module
//
// String-based datetime parsing and decomposition functions.
// All datetimes are represented as plain strings in ISO 8601 format.
// These functions validate and decompose datetime strings into parts
// without pulling in heavy datetime libraries.
//
// Supports the four TOML datetime variants:
//   Offset datetime:  2024-05-15T07:32:00Z   or  2024-05-15T07:32:00+02:00
//   Local datetime:   2024-05-15T07:32:00
//   Local date:       2024-05-15
//   Local time:       07:32:00   or  07:32:00.123456  or  07:32 (seconds omitted)
//
// Import with: import "std/datetime"
//
// This source file is part of the hica open source project
// Copyright (C) 2026 Claes Adamsson <claes.adamsson@gmail.com>
//
// See https://github.com/cladam/hica/blob/main/LICENSE for license information

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

// all_digits is provided by prelude/glob.hc

// Parse a substring as an integer, returning None on failure
pub fun parse_part(s: string, start: int, len: int) : maybe<int> =>
  parse_int(s[start:start + len])

// Check if a value falls within an inclusive range
pub fun in_range(n: int, lo: int, hi: int) : bool => n >= lo && n <= hi

// Days in a given month (handles leap years)
pub fun days_in_month(year: int, month: int) : int =>
  match month {
    1 => 31,
    2 => if (year % 4 == 0 && year % 100 != 0) || year % 400 == 0 { 29 } else { 28 },
    3 => 31,
    4 => 30,
    5 => 31,
    6 => 30,
    7 => 31,
    8 => 31,
    9 => 30,
    10 => 31,
    11 => 30,
    12 => 31,
    _ => 0
  }

// ---------------------------------------------------------------------------
// Validation
// ---------------------------------------------------------------------------

// Validate a date string: YYYY-MM-DD
pub fun is_valid_date(s: string) : bool =>
  if str_length(s) != 10 { false }
  else if s[4:5] != "-" || s[7:8] != "-" { false }
  else if !all_digits(s[0:4]) || !all_digits(s[5:7]) || !all_digits(s[8:10]) { false }
  else {
    match parse_int(s[0:4]) {
      Some(y) => match parse_int(s[5:7]) {
        Some(m) => match parse_int(s[8:10]) {
          Some(d) => in_range(m, 1, 12) && in_range(d, 1, days_in_month(y, m)),
          None => false
        },
        None => false
      },
      None => false
    }
  }

// Validate HH:MM (seconds omitted)
pub fun is_valid_time_short(s: string) : bool =>
  match parse_int(s[0:2]) {
    Some(h) => match parse_int(s[3:5]) {
      Some(m) => in_range(h, 0, 23) && in_range(m, 0, 59),
      None => false
    },
    None => false
  }

// Validate HH:MM:SS with optional fractional seconds
pub fun is_valid_time_full(s: string) : bool =>
  if !all_digits(s[6:8]) { false }
  else {
    let hh = parse_int(s[0:2])
    let mm = parse_int(s[3:5])
    let ss = parse_int(s[6:8])
    match hh {
      Some(h) => match mm {
        Some(m) => match ss {
          Some(sec) => {
            let base_ok = in_range(h, 0, 23) && in_range(m, 0, 59) && in_range(sec, 0, 59)
            if str_length(s) == 8 { base_ok }
            else if s[8:9] == "." {
              let frac = s[9:]
              base_ok && str_length(frac) > 0 && all_digits(frac)
            }
            else { false }
          },
          None => false
        },
        None => false
      },
      None => false
    }
  }

// Validate a time string: HH:MM:SS, HH:MM:SS.fraction, or HH:MM (seconds omitted)
pub fun is_valid_time(s: string) : bool =>
  if str_length(s) < 5 { false }
  else if s[2:3] != ":" { false }
  else if !all_digits(s[0:2]) || !all_digits(s[3:5]) { false }
  else if str_length(s) == 5 { is_valid_time_short(s) }
  else if str_length(s) >= 8 && s[5:6] == ":" { is_valid_time_full(s) }
  else { false }

// Validate an offset: Z, +HH:MM, or -HH:MM
pub fun is_valid_offset(s: string) : bool =>
  if s == "Z" || s == "z" { true }
  else if str_length(s) != 6 { false }
  else {
    let sign = s[0:1]
    if sign != "+" && sign != "-" { false }
    else if s[3:4] != ":" { false }
    else if !all_digits(s[1:3]) || !all_digits(s[4:6]) { false }
    else {
      match parse_int(s[1:3]) {
        Some(h) => match parse_int(s[4:6]) {
          Some(m) => in_range(h, 0, 23) && in_range(m, 0, 59),
          None => false
        },
        None => false
      }
    }
  }

// Check if rest (time+offset) is valid with Z/z offset
pub fun check_z_offset(rest: string) : bool {
  let zi = match index_of(rest, "Z") { Some(i) => i, None => match index_of(rest, "z") { Some(i) => i, None => 0 } }
  let t = rest[0:zi]
  is_valid_time(t) && is_valid_offset(rest[zi:])
}

// Check if rest (time+offset) is valid with +/-HH:MM offset
pub fun check_numeric_offset(rest: string) : bool {
  if str_length(rest) < 11 { false }
  else {
    let sign_pos = str_length(rest) - 6
    let sign_char = rest[sign_pos:sign_pos + 1]
    if sign_char != "+" && sign_char != "-" { false }
    else {
      let t = rest[0:sign_pos]
      let o = rest[sign_pos:]
      is_valid_time(t) && is_valid_offset(o)
    }
  }
}

// Validate an ISO 8601 offset datetime: YYYY-MM-DDThh:mm[:ss[.frac]]Z/±HH:MM
pub fun is_iso_datetime(s: string) : bool =>
  if str_length(s) < 17 { false }
  else {
    let sep = s[10:11]
    if sep != "T" && sep != "t" && sep != " " { false }
    else if !is_valid_date(s[0:10]) { false }
    else {
      let rest = s[11:]
      if contains(rest, "Z") || contains(rest, "z") { check_z_offset(rest) }
      else { check_numeric_offset(rest) }
    }
  }

// Validate a local datetime: YYYY-MM-DDThh:mm[:ss[.frac]] (no offset)
pub fun is_local_datetime(s: string) : bool =>
  if str_length(s) < 16 { false }
  else {
    let sep = s[10:11]
    if sep != "T" && sep != "t" && sep != " " { false }
    else {
      is_valid_date(s[0:10]) && is_valid_time(s[11:])
    }
  }

// Validate a local date: YYYY-MM-DD
pub fun is_local_date(s: string) : bool => is_valid_date(s)

// Validate a local time: HH:MM:SS[.frac]
pub fun is_local_time(s: string) : bool => is_valid_time(s)

// ---------------------------------------------------------------------------
// Decomposition
// ---------------------------------------------------------------------------

// Parse a date string into (year, month, day) or Err
pub fun date_parts(s: string) : result<(int, int, int), string> =>
  if !is_valid_date(s) { Err("invalid date: " + s) }
  else {
    match parse_int(s[0:4]) {
      Some(y) => match parse_int(s[5:7]) {
        Some(m) => match parse_int(s[8:10]) {
          Some(d) => Ok((y, m, d)),
          None => Err("invalid day")
        },
        None => Err("invalid month")
      },
      None => Err("invalid year")
    }
  }

// Parse a time string into (hour, minute, second) or Err
// Fractional seconds are truncated. Seconds-omitted times return 0 for seconds.
pub fun time_parts(s: string) : result<(int, int, int), string> =>
  if !is_valid_time(s) { Err("invalid time: " + s) }
  else if str_length(s) == 5 {
    // HH:MM — seconds omitted
    match parse_int(s[0:2]) {
      Some(h) => match parse_int(s[3:5]) {
        Some(m) => Ok((h, m, 0)),
        None => Err("invalid minute")
      },
      None => Err("invalid hour")
    }
  }
  else {
    match parse_int(s[0:2]) {
      Some(h) => match parse_int(s[3:5]) {
        Some(m) => match parse_int(s[6:8]) {
          Some(sec) => Ok((h, m, sec)),
          None => Err("invalid second")
        },
        None => Err("invalid minute")
      },
      None => Err("invalid hour")
    }
  }

// Extract the date portion from a datetime string
pub fun datetime_date(s: string) : result<string, string> =>
  if str_length(s) >= 10 && is_valid_date(s[0:10]) { Ok(s[0:10]) }
  else { Err("no valid date in: " + s) }

// Strip offset from a time+offset string to get just the time portion
pub fun strip_offset(rest: string) : string =>
  if contains(rest, "Z") || contains(rest, "z") {
    match index_of(rest, "Z") { Some(i) => rest[0:i], None => match index_of(rest, "z") { Some(i) => rest[0:i], None => rest } }
  } else if str_length(rest) >= 11 && (rest[str_length(rest) - 6:str_length(rest) - 5] == "+" || rest[str_length(rest) - 6:str_length(rest) - 5] == "-") {
    rest[0:str_length(rest) - 6]
  } else {
    rest
  }

// Extract the time portion from a local or offset datetime string
pub fun datetime_time(s: string) : result<string, string> =>
  if str_length(s) < 16 { Err("string too short for datetime") }
  else {
    let sep = s[10:11]
    if sep != "T" && sep != "t" && sep != " " { Err("no datetime separator found") }
    else {
      let time_part = strip_offset(s[11:])
      if is_valid_time(time_part) { Ok(time_part) }
      else { Err("invalid time portion") }
    }
  }

// Extract the offset portion from an offset datetime, or None for local
pub fun datetime_offset(s: string) : maybe<string> =>
  if contains(s, "Z") { Some("Z") }
  else if contains(s, "z") { Some("Z") }
  else if str_length(s) >= 22 && (s[str_length(s) - 6:str_length(s) - 5] == "+" || s[str_length(s) - 6:str_length(s) - 5] == "-") {
    let o = s[str_length(s) - 6:]
    if is_valid_offset(o) { Some(o) } else { None }
  }
  else { None }

// Classify a datetime string into its variant
pub fun datetime_kind(s: string) : string =>
  if is_local_time(s) { "local-time" }
  else if is_local_date(s) && str_length(s) == 10 { "local-date" }
  else if is_iso_datetime(s) { "offset-datetime" }
  else if is_local_datetime(s) { "local-datetime" }
  else { "invalid" }

// ---------------------------------------------------------------------------
// Comparison
// ---------------------------------------------------------------------------

// Compare two date strings lexicographically (ISO 8601 sorts correctly).
// Returns -1 if d1 < d2, 0 if equal, 1 if d1 > d2.
// Both must be valid dates; returns 0 on invalid input.
pub fun date_cmp(d1: string, d2: string) : int =>
  if !is_valid_date(d1) || !is_valid_date(d2) { 0 }
  else if d1 < d2 { -1 }
  else if d1 > d2 { 1 }
  else { 0 }

// Compare two time strings (HH:MM:SS[.frac]).
pub fun time_cmp(t1: string, t2: string) : int =>
  if !is_valid_time(t1) || !is_valid_time(t2) { 0 }
  else if t1 < t2 { -1 }
  else if t1 > t2 { 1 }
  else { 0 }

// Compare two local datetime strings.
pub fun datetime_cmp(d1: string, d2: string) : int =>
  if !is_local_datetime(d1) || !is_local_datetime(d2) { 0 }
  else if d1 < d2 { -1 }
  else if d1 > d2 { 1 }
  else { 0 }

// True if d1 is strictly before d2 (works for dates and local datetimes).
pub fun is_before(d1: string, d2: string) : bool =>
  if is_valid_date(d1) && is_valid_date(d2) { d1 < d2 }
  else if is_local_datetime(d1) && is_local_datetime(d2) { d1 < d2 }
  else if is_valid_time(d1) && is_valid_time(d2) { d1 < d2 }
  else { false }

// ---------------------------------------------------------------------------
// Offset manipulation
// ---------------------------------------------------------------------------

// Convert an offset string (Z, +HH:MM, -HH:MM) to total minutes.
// Z and +00:00 return Ok(0), +02:00 returns Ok(120), -05:30 returns Ok(-330).
pub fun offset_to_minutes(s: string) : result<int, string> =>
  if s == "Z" || s == "z" { Ok(0) }
  else if !is_valid_offset(s) { Err("invalid offset: " + s) }
  else {
    let sign = if s[0:1] == "-" { -1 } else { 1 }
    match parse_int(s[1:3]) {
      Some(h) => match parse_int(s[4:6]) {
        Some(m) => Ok(sign * (h * 60 + m)),
        None => Err("invalid offset minutes")
      },
      None => Err("invalid offset hours")
    }
  }

// ---------------------------------------------------------------------------
// Weekday calculation (Tomohiko Sakamoto's algorithm)
// ---------------------------------------------------------------------------

// Helper: look up a value from a small list by index
pub fun list_int_nth(xs: list<int>, i: int) : int => match xs {
  [] => 0,
  [x, ..rest] => if i == 0 { x } else { list_int_nth(rest, i - 1) }
}

// Day of week for a valid date. Returns "monday" through "sunday".
pub fun day_of_week(s: string) : result<string, string> =>
  if !is_valid_date(s) { Err("invalid date: " + s) }
  else {
    match date_parts(s) {
      Err(e) => Err(e),
      Ok(parts) => {
        // Sakamoto's algorithm
        let y = if parts.1 < 3 { parts.0 - 1 } else { parts.0 }
        let t = [0, 3, 2, 5, 0, 3, 5, 1, 4, 6, 2, 4]
        let idx = (y + y / 4 - y / 100 + y / 400 + list_int_nth(t, parts.1 - 1) + parts.2) % 7
        let names = ["sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday"]
        match idx {
          0 => Ok("sunday"),
          1 => Ok("monday"),
          2 => Ok("tuesday"),
          3 => Ok("wednesday"),
          4 => Ok("thursday"),
          5 => Ok("friday"),
          6 => Ok("saturday"),
          _ => Err("unreachable")
        }
      }
    }
  }

// ---------------------------------------------------------------------------
// Epoch / duration helpers
//
// Built on the now_unix(), now_iso(), and unix_to_iso() built-in primitives
// (backed by Koka std/time — no import needed in calling code).
//
// Unix epoch timestamps are plain \`int\` values (seconds since 1970-01-01Z).
// Store them with now_unix(), compare with secs_since / days_since, and
// convert back to human-readable strings with unix_to_iso().
// ---------------------------------------------------------------------------

// Seconds elapsed since a stored Unix epoch timestamp.
pub fun secs_since(epoch: int) => now_unix() - epoch

// Minutes elapsed since a stored Unix epoch timestamp.
pub fun mins_since(epoch: int) => secs_since(epoch) / 60

// Hours elapsed since a stored Unix epoch timestamp.
pub fun hours_since(epoch: int) => secs_since(epoch) / 3600

// Days elapsed since a stored Unix epoch timestamp.
pub fun days_since(epoch: int) => secs_since(epoch) / 86400

// True if the stored epoch is older than \`days\` days from now.
pub fun is_older_than_days(epoch: int, days: int) => days_since(epoch) >= days

// True if the stored epoch is older than \`hours\` hours from now.
pub fun is_older_than_hours(epoch: int, hours: int) => hours_since(epoch) >= hours

// Absolute difference in seconds between two epoch timestamps.
pub fun secs_diff(a: int, b: int) =>
  let d = a - b
  if d < 0 { -d } else { d }

// Absolute difference in days between two epoch timestamps.
pub fun days_diff(a: int, b: int) => secs_diff(a, b) / 86400

// ---------------------------------------------------------------------------
// Date string → Unix epoch
// ---------------------------------------------------------------------------
// Convert a "YYYY-MM-DD" string to a Unix epoch integer (seconds since
// 1970-01-01T00:00:00Z at midnight UTC). Returns -1 if the date is invalid.
// Useful for storing and comparing calendar dates as plain integers.
//
//   let deadline = date_to_unix("2026-12-31")
//   println(days_since(deadline) < 0)   // true if still in the future

// Internal: sum of days in months 1..(m-1) of year y (handles leap years)
pub fun months_days_sum(y: int, m: int, acc: int) =>
  if m <= 1 { acc }
  else { months_days_sum(y, m - 1, acc + days_in_month(y, m - 1)) }

// Internal: convert a validated (year, month, day) triple to a Unix epoch
pub fun date_to_unix_parts(y: int, m: int, d: int) {
  let b = y - 1
  let leap_count = b/4 - b/100 + b/400 - 477
  let year_days = (y - 1970) * 365 + leap_count
  let month_days = months_days_sum(y, m, 0)
  let total_days = year_days + month_days + d - 1
  total_days * 86400
}

// Convert a "YYYY-MM-DD" string to a Unix epoch integer (midnight UTC).
// Returns -1 for invalid dates. Supports 1970-01-01 and later.
pub fun date_to_unix(s: string) =>
  match date_parts(s) {
    Err(_) => -1,
    Ok(parts) => date_to_unix_parts(parts.0, parts.1, parts.2)
  }`],
  ["std/env", `// hica – environment variable helpers
//
// Convenience wrappers around the built-in get_env().
// Import with: import "std/env"
//
// This source file is part of the hica open source project
// Copyright (C) 2026 Claes Adamsson <claes.adamsson@gmail.com>
//
// See https://github.com/cladam/hica/blob/main/LICENSE for license information

// Get an environment variable, or return a default value if not set
pub fun env_or(key, default) => match get_env(key) {
  Some(v) => v,
  None => default
}

// Get a required environment variable.
// Prints an error to stderr and returns "" if the variable is not set.
pub fun env_require(key) => match get_env(key) {
  Some(v) => v,
  None => {
    eprintln("Error: environment variable '" + key + "' is required but not set")
    ""
  }
}

// Get an environment variable and parse it as an integer.
// Returns None if the variable is not set or is not a valid integer.
pub fun env_int(key) => match get_env(key) {
  Some(v) => parse_int(v),
  None => None
}`],
  ["std/dotenv", `// hica – dotenv stdlib module
//
// Reads .env files and loads key-value pairs into the process environment.
// Import with: import "std/dotenv"
//
// Usage:
//   import "std/dotenv"
//
//   fun main() {
//     dotenv_load(".env")        // load .env; skip already-set vars
//     let db = env_or("DB_URL", "sqlite://dev.db")
//     println("DB: {db}")
//   }
//
// .env format (subset of the de facto standard):
//   KEY=value
//   KEY="quoted value"
//   KEY='single quoted'
//   export KEY=value        # optional export keyword
//   # this is a comment
//
// Note: dotenv_load() must be called before get_env()/env_or() for the
// loaded values to be visible, because the Koka env cache is computed once
// on first access.
//
// This source file is part of the hica open source project
// Copyright (C) 2026 Claes Adamsson <claes.adamsson@gmail.com>
//
// See https://github.com/cladam/hica/blob/main/LICENSE for license information

// ---------------------------------------------------------------------------
// Parsing helpers
// ---------------------------------------------------------------------------

// Strip surrounding single or double quotes from a value string.
// Falls back to trimming whitespace if no quotes are present.
pub fun dotenv_strip_quotes(s: string) : string {
  let n = str_length(s)
  if n >= 2 && starts_with(s, "\\"") && ends_with(s, "\\"") { s[1:n-1] }
  else if n >= 2 && starts_with(s, "'") && ends_with(s, "'") { s[1:n-1] }
  else { trim(s) }
}

// Given a raw \`KEY=VALUE\` string and the position of \`=\`, return (key, value).
// Returns None if the key is empty.
pub fun dotenv_parse_kv(s: string, i: int) : maybe<(string, string)> {
  let key = trim(s[:i])
  if str_length(key) == 0 { None }
  else { Some((key, dotenv_strip_quotes(s[i+1:]))) }
}

// Parse one line of .env content into a (key, value) pair.
// Returns None for blank lines, comment lines, and malformed entries.
pub fun dotenv_parse_line(line: string) : maybe<(string, string)> {
  let trimmed = trim(line)
  if str_length(trimmed) == 0 { None }
  else if starts_with(trimmed, "#") { None }
  else {
    let s = if starts_with(trimmed, "export ") { trimmed[7:] } else { trimmed }
    match index_of(s, "=") {
      None => None,
      Some(i) => dotenv_parse_kv(s, i)
    }
  }
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

// Parse a multi-line .env format string into a list of (key, value) pairs.
// Blank lines and # comments are ignored.
pub fun dotenv_parse(content: string) : list<(string, string)> {
  fold(split(content, "\\n"), [], (acc, line) => match dotenv_parse_line(line) {
    None => acc,
    Some(pair) => acc + [pair]
  })
}

// Apply a list of (key, value) pairs to the environment.
// Variables already set in the environment are NOT overwritten.
// Uses setenv(..., 0) at the OS level — never forces Koka's env cache.
pub fun dotenv_apply(pairs) {
  foreach(pairs, (p) => match p {
    (k, v) => set_env_nooverwrite(k, v)
  })
}

// Apply a list of (key, value) pairs to the environment, overwriting existing values.
pub fun dotenv_apply_override(pairs) {
  foreach(pairs, (p) => match p {
    (k, v) => set_env(k, v)
  })
}

// Load a .env file into the process environment.
// Variables already set in the environment are NOT overwritten (safe default).
// Silently ignores missing or unreadable files.
pub fun dotenv_load(path: string) {
  match read_file(path) {
    Ok(content) => dotenv_apply(dotenv_parse(content)),
    Err(_) => { }
  }
}

// Load a .env file, overwriting any existing environment variables.
// Silently ignores missing or unreadable files.
pub fun dotenv_load_override(path: string) {
  match read_file(path) {
    Ok(content) => dotenv_apply_override(dotenv_parse(content)),
    Err(_) => { }
  }
}`],
  ["std/log", `// hica standard library — structured logging
//
// Level-filtered, named logging with optional ANSI color and file output.
// Inspired by Python's logging module and the pylogging Rust crate.
// Import with: import "std/log"
//
// Usage:
//   import "std/log"
//
//   fun main() {
//     let log = make_logger("myapp")
//     log_info(log, "server started on port 8080")
//     log_warning(log, "disk usage above 85%")
//     log_error(log, "connection refused")
//   }
//
//   // Customize level, colors, or file sink:
//   fun main() {
//     let log = make_logger("myapp")
//       |> logger_set_level(Debug)
//       |> logger_set_file("app.log")
//     log_debug(log, "verbose diagnostic info")
//   }
//
// This source file is part of the hica open source project
// Copyright (C) 2026 Claes Adamsson <claes.adamsson@gmail.com>
//
// See https://github.com/cladam/hica/blob/main/LICENSE for license information

// ---------------------------------------------------------------------------
// Log level
// ---------------------------------------------------------------------------

// Log severity levels, from least to most severe.
// Messages below the logger's configured level are discarded without output.
pub type LogLevel {
  Debug,
  Info,
  Warning,
  Error,
  Critical
}

// Numeric value for level comparisons (higher = more severe).
// Debug=0, Info=1, Warning=2, Error=3, Critical=4.
pub fun level_value(lv: LogLevel) : int => match lv {
  Debug    => 0,
  Info     => 1,
  Warning  => 2,
  Error    => 3,
  Critical => 4
}

// Human-readable level name used in formatted output.
pub fun level_name(lv: LogLevel) : string => match lv {
  Debug    => "DEBUG",
  Info     => "INFO",
  Warning  => "WARNING",
  Error    => "ERROR",
  Critical => "CRITICAL"
}

// ---------------------------------------------------------------------------
// Logger struct
// ---------------------------------------------------------------------------

// A named logger with a minimum level, optional ANSI color output, and an
// optional file sink. Loggers are immutable values — use the logger_set_*
// helpers to produce a modified copy.
//
// Fields:
//   name      — label shown in formatted output, e.g. "myapp" or "myapp.db"
//   level     — minimum severity; messages below this threshold are discarded
//   use_color — when true, wraps console output in per-level ANSI color codes
//   log_file  — path to an append log file; "" disables file logging
pub struct Logger {
  name: string,
  level: LogLevel,
  use_color: bool,
  log_file: string
}

// Create a logger with the given name, level Info, colors on, no file sink.
pub fun make_logger(name: string) : Logger =>
  Logger { name: name, level: Info, use_color: true, log_file: "" }

// Create a logger with an explicit minimum level.
pub fun make_logger_level(name: string, lv: LogLevel) : Logger =>
  Logger { name: name, level: lv, use_color: true, log_file: "" }

// Return a copy of the logger with a new minimum level.
pub fun logger_set_level(lg: Logger, lv: LogLevel) : Logger =>
  Logger { name: lg.name, level: lv, use_color: lg.use_color, log_file: lg.log_file }

// Return a copy of the logger with color output toggled.
pub fun logger_set_color(lg: Logger, enabled: bool) : Logger =>
  Logger { name: lg.name, level: lg.level, use_color: enabled, log_file: lg.log_file }

// Return a copy of the logger that also appends records to the given file.
// Pass "" to disable file logging. File records are always plain text (no ANSI).
pub fun logger_set_file(lg: Logger, path: string) : Logger =>
  Logger { name: lg.name, level: lg.level, use_color: lg.use_color, log_file: path }

// True if a message at the given level would be emitted by this logger.
pub fun log_enabled(lg: Logger, lv: LogLevel) : bool =>
  level_value(lv) >= level_value(lg.level)

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

// ESC character (ASCII 27) for ANSI escape sequences.
pub fun log_esc() : string => char_to_string(chr(27))

// Wrap text in an ANSI SGR code, resetting to default after.
pub fun log_ansi(code: string, s: string) : string =>
  log_esc() + "[" + code + "m" + s + log_esc() + "[0m"

// Per-level ANSI color, matching the pylogging color scheme:
//   Debug=gray, Info=blue, Warning=yellow, Error=red, Critical=deep red
pub fun log_colorize(lv: LogLevel, s: string) : string => match lv {
  Debug    => log_ansi("90", s),
  Info     => log_ansi("34", s),
  Warning  => log_ansi("33", s),
  Error    => log_ansi("31", s),
  Critical => log_ansi("38;5;88", s)
}

// Format a log record as "[LEVEL] name: message".
pub fun log_format(name: string, lv: LogLevel, msg: string) : string =>
  "[" + level_name(lv) + "] " + name + ": " + msg

// Append a plain-text line to a log file (read → append → write).
// Silently ignores write failures — logging should never crash the program.
pub fun log_append_file(path: string, line: string) {
  let existing = match read_file(path) {
    Ok(content) => content,
    Err(_) => ""
  }
  match write_file(path, existing + line + "\\n") {
    Ok(_) => { },
    Err(_) => { }
  }
}

// Emit a single record: filter by level, colorize for console, write to file.
// Error and Critical records go to stderr; all others go to stdout.
pub fun log_emit(lg: Logger, lv: LogLevel, msg: string) {
  if log_enabled(lg, lv) {
    let line = log_format(lg.name, lv, msg)
    let output = if lg.use_color { log_colorize(lv, line) } else { line }
    match lv {
      Error    => eprintln(output),
      Critical => eprintln(output),
      _        => println(output)
    }
    if !is_empty(lg.log_file) {
      log_append_file(lg.log_file, line)
    } else { }
  } else { }
}

// ---------------------------------------------------------------------------
// Public logging functions
// ---------------------------------------------------------------------------

// Emit a DEBUG record (level 0). Verbose diagnostic output, disabled by default.
pub fun log_debug(lg: Logger, msg: string) { log_emit(lg, Debug, msg) }

// Emit an INFO record (level 1). Normal operational messages (default minimum).
pub fun log_info(lg: Logger, msg: string) { log_emit(lg, Info, msg) }

// Emit a WARNING record (level 2). Unexpected situation that is not yet an error.
pub fun log_warning(lg: Logger, msg: string) { log_emit(lg, Warning, msg) }

// Emit an ERROR record (level 3). A failure that should be investigated. Goes to stderr.
pub fun log_error(lg: Logger, msg: string) { log_emit(lg, Error, msg) }

// Emit a CRITICAL record (level 4). Fatal or near-fatal condition. Goes to stderr.
pub fun log_critical(lg: Logger, msg: string) { log_emit(lg, Critical, msg) }`],
  ["std/trusted", `// hica – std/trusted — type-safe string trust boundaries
//
// Provides the Trusted type: a string that has explicitly crossed a trust
// boundary through a smart constructor or validator.
//
// Usage: import "std/trusted"
//
// ── The validation ladder ────────────────────────────────────────────────
//
// Apply validators in this order (cheapest first) to keep rejection fast
// and deny attackers the expensive steps:
//
//   1. Origin      — does this come from a trusted source? (app-level)
//   2. Size        — validate_range / validate_maxlen  (constant time)
//   3. Characters  — validate_alnum / validate_with    (scan, no parse)
//   4. Format      — validate_with(s, regex_pred)      (parser / regex)
//   5. Semantic    — DB / state check                  (app-level)
//
// std/trusted covers rungs 2-4. Rungs 1 and 5 are intentionally left to
// application code because they require external context (network origin,
// database state). This is by design: those checks are expensive, and the
// type system ensures callers consciously perform them.
//
// Once a value is Trusted, \`trusted_value(t)\` is the only way to read it
// back. That explicit unwrap is the right place to decide whether to log the
// raw string — you almost never should (log the fact of rejection, not the
// rejected input itself).
//
// This source file is part of the hica open source project
// Copyright (C) 2026 Claes Adamsson <claes.adamsson@gmail.com>
//
// See https://github.com/cladam/hica/blob/main/LICENSE for license information

// The Trusted type. The constructor is private to this module —
// callers must use trust() or a validate_* function.
pub struct Trusted priv { data: string }

// Explicit trust marker: "I have verified this string is safe."
// Use only when you are certain the value is already known-good.
pub fun trust(s: string) : Trusted => Trusted { data: s }

// Unwrap the inner string from a Trusted value.
pub fun trusted_value(t: Trusted) : string => t.data

// ---------------------------------------------------------------------------
// Validators — each returns Some(Trusted) on success, None on failure
// ---------------------------------------------------------------------------

// Accept any non-empty string.
pub fun validate_nonempty(s: string) : maybe<Trusted> =>
  if str_length(s) > 0 { Some(Trusted { data: s }) }
  else { None }

// Accept a string whose length does not exceed \`max\` characters.
// Rung 2 of the validation ladder: size upper bound.
pub fun validate_maxlen(s: string, max: int) : maybe<Trusted> =>
  if str_length(s) <= max { Some(Trusted { data: s }) }
  else { None }

// Accept a string whose length is between \`min\` and \`max\` (inclusive).
// Rung 2 of the validation ladder: both size bounds at once.
// Prefer this over chaining validate_nonempty + validate_maxlen.
pub fun validate_range(s: string, min_len: int, max_len: int) : maybe<Trusted> =>
  if str_length(s) >= min_len && str_length(s) <= max_len { Some(Trusted { data: s }) }
  else { None }

// Accept a non-empty string containing only alphanumeric characters (a-z A-Z 0-9).
// Rung 3 of the validation ladder: character-set check (any order, no parsing).
// Useful for identifiers, tokens, and simple keys.
pub fun validate_alnum(s: string) : maybe<Trusted> =>
  if all_alnum(s) { Some(Trusted { data: s }) }
  else { None }

// Accept a string that satisfies a caller-supplied predicate.
// Rung 3 (character check) or Rung 4 (format/regex) depending on the predicate.
// This is the escape hatch for custom validation logic:
//
//   let t = validate_with(input, (s) => starts_with(s, "usr_"))
pub fun validate_with(s: string, pred: (string) -> bool) : maybe<Trusted> =>
  if pred(s) { Some(Trusted { data: s }) }
  else { None }

// ---------------------------------------------------------------------------
// Combinators
// ---------------------------------------------------------------------------

// Chain two validators: both must pass.
// validate_and(validate_nonempty(s), validate_maxlen(s, 64))
pub fun validate_and(a: maybe<Trusted>, b: maybe<Trusted>) : maybe<Trusted> =>
  match a {
    None => None,
    Some(_) => b
  }

// Unwrap a trusted value with a fallback string (already trusted).
pub fun trusted_or(t: maybe<Trusted>, fallback: string) : Trusted =>
  match t {
    Some(v) => v,
    None => Trusted { data: fallback }
  }`],
  ["std/stream", `// stream.hc — Lazy stream processing for hica
//
// Built-in stdlib module, auto-imported when stream<a> operations are used.
// Users can import via: import "std/stream"`],
  ["std/xform", `// xform.hc — Pipeline transducers for hica
//
// Build reusable stream transformations without allocating intermediate collections,
// and apply them to any compatible list/stream source.
//
// This is additive on top of std/stream.

import "std/stream"
import "std/list"

// Start of a chain (1-argument constructors)
pub fun xf_filter(pred) =>
  (s) => as_stream(s) |> filter(pred)

pub fun xf_map_start(f) =>
  (s) => as_stream(s) |> map(f)

pub fun xf_take_start(n) =>
  (s) => as_stream(s) |> take(n)

pub fun xf_take_while_start(pred) =>
  (s) => as_stream(s) |> take_while(pred)

pub fun xf_drop_while_start(pred) =>
  (s) => as_stream(s) |> drop_while(pred)

pub fun xf_flat_map_start(f) =>
  (s) => as_stream(s) |> flat_map(f)

// Middle of a chain (2-argument composition steps)
pub fun xf_map(xform, f) =>
  (s) => as_stream(s) |> xform |> as_stream |> map(f)

pub fun xf_filter_with(xform, pred) =>
  (s) => as_stream(s) |> xform |> as_stream |> filter(pred)

pub fun xf_take(xform, n) =>
  (s) => as_stream(s) |> xform |> as_stream |> take(n)

pub fun xf_take_while(xform, pred) =>
  (s) => as_stream(s) |> xform |> as_stream |> take_while(pred)

pub fun xf_drop_while(xform, pred) =>
  (s) => as_stream(s) |> xform |> as_stream |> drop_while(pred)

pub fun xf_flat_map(xform, f) =>
  (s) => as_stream(s) |> xform |> as_stream |> flat_map(f)

// Base identity/initialization transducer if someone wants to start with a standard 2-argument operation
pub fun xf_start() =>
  (s) => as_stream(s)

// Apply the transducer to a compatible source list and collect the results.
pub fun transduce(xs, xform) =>
  stream(xs) |> xform |> collect()`],
  ["std/nel", `// hica — std/nel — Non-empty list of strings
// Import with: import "std/nel"

pub type Nel {
  Nel(head: string, tail: list<string>)
}

// Create a Nel with a single element
pub fun nel_of(x: string) : Nel =>
  Nel(x, [])

// Convert a Nel to a standard list of strings
pub fun nel_to_list(n: Nel) : list<string> => match n {
  Nel(h, t) => [h] + t
}

// Get the head of the Nel
pub fun nel_head(n: Nel) : string => match n {
  Nel(h, _) => h
}

// Map a function over each element of the Nel, returning a new Nel
pub fun nel_map(n: Nel, f: (string) -> string) : Nel => match n {
  Nel(h, t) => Nel(f(h), map(t, f))
}

// Concatenate two Nel values into a single Nel
pub fun nel_concat(a: Nel, b: Nel) : Nel => match a {
  Nel(ah, at) => match b {
    Nel(bh, bt) => Nel(ah, at + [bh] + bt)
  }
}`],
  ["std/validated", `// hica — std/validated — Error-accumulating validation
// Import with: import "std/validated"

import "std/nel"

// We use string for the Valid value. Since hica functions are polymorphic,
// combinators like zip_validated can map over different types using HM inference.
pub type Validated {
  Valid(value: string),
  Invalid(errors: Nel)
}

// Wrap a success value
pub fun valid(x: string) : Validated =>
  Valid(x)

// Wrap a single failure message
pub fun invalid(msg: string) : Validated =>
  Invalid(nel_of(msg))

// Map a function over a valid value
pub fun map_validated(v: Validated, f: (string) -> string) : Validated => match v {
  Valid(x)   => Valid(f(x)),
  Invalid(e) => Invalid(e)
}

// Combine/zip two validations. If both are valid, applies f.
// If either or both are invalid, accumulates/merges all errors!
pub fun zip_validated(v1: Validated, v2: Validated, f: (string, string) -> string) : Validated =>
  match v1 {
    Valid(x1) => match v2 {
      Valid(x2)   => Valid(f(x1, x2)),
      Invalid(e2) => Invalid(e2)
    },
    Invalid(e1) => match v2 {
      Valid(_)    => Invalid(e1),
      Invalid(e2) => Invalid(nel_concat(e1, e2))
    }
  }

// Convert a Validated to a standard Result
pub fun as_result(v: Validated) : result<string, list<string>> => match v {
  Valid(x)   => Ok(x),
  Invalid(e) => Err(nel_to_list(e))
}

// Convert a standard Result to a Validated
pub fun from_result(r: result<string, string>) : Validated => match r {
  Ok(x)  => Valid(x),
  Err(e) => invalid(e)
}`],
];
