// Auto-generated by build-playground.sh — do not edit
const STDLIB_SOURCES = [
  ["std/ops", `// hica – operator prelude
//
// Operators as first-class functions, inspired by Python's operator module.
// Pass these to map, filter, fold, etc. instead of writing lambdas.
//
//   fold(xs, 0, add)       // instead of fold(xs, 0, fun(a, b) => a + b)
//   filter(xs, is_positive) // instead of filter(xs, fun(n) => n > 0)
//
// This source file is part of the hica open source project
// Copyright (C) 2026 Claes Adamsson <claes.adamsson@gmail.com>
//
// See https://github.com/cladam/hica/blob/main/LICENSE for license information

// --- Arithmetic ---

pub fun add(a, b) => a + b

pub fun sub(a, b) => a - b

pub fun mul(a, b) => a * b

pub fun div(a, b) => a / b

pub fun mod(a, b) => a % b

pub fun neg(n) => -n

// --- Comparison ---

pub fun lt(a, b) => a < b

pub fun le(a, b) => a <= b

pub fun gt(a, b) => a > b

pub fun ge(a, b) => a >= b

// --- Logical ---

pub fun not_(b) => !b

pub fun and_(a, b) => a && b

pub fun or_(a, b) => a || b

// --- Predicates ---

pub fun is_positive(n) => n > 0

pub fun is_negative(n) => n < 0

pub fun is_zero(n) => n == 0

pub fun is_even(n) => n % 2 == 0

pub fun is_odd(n) => n % 2 != 0

// --- Utility ---

pub fun identity(x) => x

//fun square(n) => n * n

//fun double(n) => n * 2`],
  ["std/list", `// hica – list prelude
//
// Higher-level list functions built on top of the list primitives
// (map, filter, fold, etc.).
//
// This source file is part of the hica open source project
// Copyright (C) 2026 Claes Adamsson <claes.adamsson@gmail.com>
//
// See https://github.com/cladam/hica/blob/main/LICENSE for license information

// --- Transformations ---

pub fun intersperse(xs, sep) => match xs {
  [] => [],
  [x] => [x],
  [x, ..rest] => [x, sep] + intersperse(rest, sep)
}

// --- Reductions ---

pub fun sum(xs) => fold(xs, 0, (a, b) => a + b)

pub fun product(xs) => fold(xs, 1, (a, b) => a * b)

pub fun scan(xs, init, f) => match xs {
  [] => [init],
  [x, ..rest] => [init] + scan(rest, f(init, x), f)
}

// --- Combining ---

pub fun zip_with(xs, ys, f) => map(zip(xs, ys), (pair) => f(pair.0, pair.1))

// --- Filtering ---

pub fun unique(xs: list<int>) : list<int> => fold(xs, [], (acc, x) => if x in acc { acc } else { acc + [x] })

// --- Splitting ---

pub fun chunks(xs, n) => match xs {
  [] => [],
  _ => [take(xs, n)] + chunks(drop(xs, n), n)
}

// --- Head/Tail helpers ---

// First element or a default value (avoids unwrapping maybe after length check)
pub fun head_or(xs, default) => match xs {
  [] => default,
  [x, ..] => x
}

// --- Prefix/Suffix predicates ---

// Take elements from the front while predicate holds
pub fun take_while(xs, pred) => match xs {
  [] => [],
  [x, ..rest] => if pred(x) { [x] + take_while(rest, pred) } else { [] }
}

// Drop elements from the front while predicate holds; return the rest
pub fun drop_while(xs, pred) => match xs {
  [] => [],
  [x, ..rest] => if pred(x) { drop_while(rest, pred) } else { xs }
}

// --- Counting ---

// Count elements matching predicate
pub fun count(xs, pred) => fold(xs, 0, (acc, x) => if pred(x) { acc + 1 } else { acc })

// --- Grouping ---

// Internal helper: insert item into existing (key, group) pair list
pub fun group_by_insert(pairs, key: string, item) => match pairs {
  [] => [(key, [item])],
  [p, ..rest] => match p {
    (k, vs) => if k == key { [(k, vs + [item])] + rest } else { [(k, vs)] + group_by_insert(rest, key, item) }
  }
}

// Group elements by key function f(x) -> string; returns list of (key, group) pairs
pub fun group_by(xs, f) => fold(xs, [], (acc, x) => group_by_insert(acc, f(x), x))

// --- Min/Max by key ---

// Internal helpers (pub required for stdlib modules)
pub fun pick_min(a, b, ka: int, kb: int) => if ka < kb { a } else { b }
pub fun pick_max(a, b, ka: int, kb: int) => if ka > kb { a } else { b }

// Element with the smallest int key (None on empty list)
pub fun min_by(xs, f) => match xs {
  [] => None,
  [first, ..rest] => Some(fold(rest, first, (best, x) => pick_min(x, best, f(x), f(best))))
}

// Element with the largest int key (None on empty list)
pub fun max_by(xs, f) => match xs {
  [] => None,
  [first, ..rest] => Some(fold(rest, first, (best, x) => pick_max(x, best, f(x), f(best))))
}`],
  ["std/string", `// hica – string stdlib module
//
// Extended string functions. Auto-import with: import "std/string"
// Functions that depend on prelude internals (pad_left, pad_right, repeat_str,
// removeprefix) stay in the prelude until std/cli is separated.
//
// This source file is part of the hica open source project
// Copyright (C) 2026 Claes Adamsson <claes.adamsson@gmail.com>
//
// See https://github.com/cladam/hica/blob/main/LICENSE for license information

// --- Counting ---

pub fun count_substr(s: string, sub: string) => length(split(s, sub)) - 1

// --- Wrapping ---

pub fun surround(s: string, wrap: string) => wrap + s + wrap

// --- Case helpers ---

pub fun capitalise(s: string) : string =>
  if str_length(s) == 0 { "" }
  else { to_upper(s[:1]) + to_lower(s[1:]) }

pub fun capwords(s: string) : string =>
  join(map(filter(split(s, " "), (w) => str_length(w) != 0), (w) => capitalise(w)), " ")

pub fun shout(s: string) : string => to_upper(s) + "!"

// --- Suffix removal ---

pub fun removesuffix(s: string, suf: string) : string =>
  if ends_with(s, suf) { s[:str_length(s) - str_length(suf)] }
  else { s }

// --- Float formatting ---

// show() for floats inherits Koka's %g formatting which drops the decimal
// point for whole numbers (1.0 → "1"). show_float always includes it,
// making it correct for formats like JSON that require 1.0 not "1".
// Scientific notation (1e+10) is left unchanged — it already signals float.
pub fun show_float(n: float) : string =>
  let s = show(n)
  if contains(s, ".") || contains(s, "e") { s }
  else { s + ".0" }`],
  ["std/term", `// hica standard library — terminal colors and styles
//
// ANSI escape code wrappers for colored/styled terminal output.
// Import with:  import "std/term"
//
// All functions wrap a string with ANSI SGR codes and reset to default after.
// Functions are composable: bold(red("error:")) works correctly.
//
// Example:
//   import "std/term"
//
//   fun main() {
//     println(green("OK"))
//     println(bold(red("error: something went wrong")))
//     println(cyan("info: ") + "all good")
//   }
//
// This source file is part of the hica open source project
// Copyright (C) 2026 Claes Adamsson <claes.adamsson@gmail.com>
//
// See https://github.com/cladam/hica/blob/main/LICENSE for license information

// ESC character (ASCII 27) — used to build ANSI escape sequences
pub fun term_esc() : string => char_to_string(chr(27))

// Apply an ANSI SGR code to text, resetting to default after.
// This is the building block for all color/style functions.
pub fun term_ansi(code: string, s: string) : string =>
  term_esc() + "[" + code + "m" + s + term_esc() + "[0m"

// ---------------------------------------------------------------------------
// Foreground colors
// ---------------------------------------------------------------------------

pub fun red(s: string) : string => term_ansi("31", s)
pub fun green(s: string) : string => term_ansi("32", s)
pub fun yellow(s: string) : string => term_ansi("33", s)
pub fun blue(s: string) : string => term_ansi("34", s)
pub fun magenta(s: string) : string => term_ansi("35", s)
pub fun cyan(s: string) : string => term_ansi("36", s)
pub fun white(s: string) : string => term_ansi("37", s)

// ---------------------------------------------------------------------------
// Text styles
// ---------------------------------------------------------------------------

pub fun bold(s: string) : string => term_ansi("1", s)
pub fun dim(s: string) : string => term_ansi("2", s)
pub fun italic(s: string) : string => term_ansi("3", s)
pub fun underline(s: string) : string => term_ansi("4", s)
pub fun strikethrough(s: string) : string => term_ansi("9", s)

// ---------------------------------------------------------------------------
// Bright foreground colors
// ---------------------------------------------------------------------------

pub fun bright_red(s: string) : string => term_ansi("91", s)
pub fun bright_green(s: string) : string => term_ansi("92", s)
pub fun bright_yellow(s: string) : string => term_ansi("93", s)
pub fun bright_blue(s: string) : string => term_ansi("94", s)
pub fun bright_cyan(s: string) : string => term_ansi("96", s)
pub fun bright_white(s: string) : string => term_ansi("97", s)

// ---------------------------------------------------------------------------
// True color (24-bit RGB) — requires a modern terminal
// Foreground: term_rgb(r, g, b, s)  — wraps s in \\e[38;2;R;G;Bm ... \\e[0m
// ---------------------------------------------------------------------------

pub fun term_rgb(r: int, g: int, b: int, s: string) : string =>
  term_esc() + "[38;2;" + show(r) + ";" + show(g) + ";" + show(b) + "m" + s + term_esc() + "[0m"

// ---------------------------------------------------------------------------
// Ilseon palette — inspired by github.com/cladam/ilseon
//
// A low-sensory, OLED-focused dark palette with organic and muted accents.
// Colours follow the "Pulse" spectrum (energy & priority) and semantic slots
// from the ilseon app theme.
//
// Requires true color terminal support (iTerm2, VS Code, most modern terminals).
// ---------------------------------------------------------------------------

pub fun ilseon_teal(s: string) : string => term_rgb(0, 191, 165, s)        // #00BFA5  TealAccent — primary action
pub fun ilseon_muted_red(s: string) : string => term_rgb(179, 95, 95, s)   // #B35F5F  MutedRed — urgent / priority high
pub fun ilseon_amber(s: string) : string => term_rgb(192, 138, 62, s)      // #C08A3E  QuietAmber — priority medium
pub fun ilseon_ochre(s: string) : string => term_rgb(226, 176, 94, s)      // #E2B05E  StatusHigh — warm ochre / high energy
pub fun ilseon_sage(s: string) : string => term_rgb(163, 169, 145, s)      // #A3A991  StatusMedium — muted sage / balanced
pub fun ilseon_slate(s: string) : string => term_rgb(125, 133, 151, s)     // #7D8597  StatusLow — steel blue-grey / low pressure
pub fun ilseon_muted_teal(s: string) : string => term_rgb(90, 155, 128, s) // #5A9B80  MutedTeal — green-teal accent
pub fun ilseon_blue_teal(s: string) : string => term_rgb(76, 154, 155, s)  // #4C9A9B  BlueTeal — secondary highlight
pub fun ilseon_slate_blue(s: string) : string => term_rgb(94, 109, 126, s) // #5E6D7E  SlateBlue — quiet UI element
pub fun ilseon_detail(s: string) : string => term_rgb(136, 136, 136, s)    // #888888  MutedDetail — secondary text / low priority

// ----------------------------------------------------------------------------
// hica unique palette
// ---------------------------------------------------------------------------- `],
];
